# Generated by Django 5.0.4 on 2024-05-03 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(verbose_name=datetime.date(2024, 5, 3))),
                ('image', models.ImageField(upload_to='blog/images/')),
            ],
        ),
    ]
